apiVersion: apps/v1
kind: Deployment
metadata: 
   name: angularclient
   labels:
     app: client
spec: 
   selector: 
      matchLabels: 
         app: client
   replicas: 2 
   template: 
     metadata: 
        labels:
           app: client 
     spec: 
       containers: 
       - name: client
         image: {{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}
         imagePullPolicy: Always
         ports: 
           - containerPort: 80       
